name: compile
on:
  push:
    branches: [ master ]
    paths-ignore:
      - "*.md"
      - "*.sh"
  pull_request:
    branches: [ master ]
    paths-ignore:
      - "*.md"
      - "*.sh"

env:
  CARGO_TERM_COLOR: always

jobs:
  build-corss:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - arm-unknown-linux-gnueabi
          - aarch64-unknown-linux-gnu
          - i686-unknown-linux-gnu
          - x86_64-pc-windows-gnu
        include:
          - target: x86_64-unknown-linux-gnu
            output: realm
          - target: aarch64-unknown-linux-gnu
            output: realm
          - target: arm-unknown-linux-gnueabi
            output: realm
          - target: i686-unknown-linux-gnu
            output: realm
          - target: x86_64-pc-windows-gnu
            output: realm.exe
    steps:
      - uses: actions/checkout@v2
      - name: install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          target: ${{ matrix.target }}
          override: true
      - name: compile
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --target=${{ matrix.target }}
      - name: upload
        uses: actions/upload-artifact@v2
        with:
          name: realm-${{ matrix.target }}
          path: target/${{ matrix.target }}/release/${{ matrix.output }}
